---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: debian-7.2.0
  - name: centos-6.5

suites:
  - name: default
    run_list: recipe[dtach::default]
    attributes:
